/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Dashboard;

import Controller.ControllerDashboard;
import View.Content.ViewCashflow;
import View.Content.ViewDashboardReal;
import View.Content.ViewKeuangan;
import View.Content.ViewProfile;
import java.awt.CardLayout;

/**
 *
 * @author Felda Muffarihati
 */
public class ViewDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewDashboard.class.getName());
    
    private ViewDashboardReal dashboardPanel;
    private ViewKeuangan keuanganPanel;
    private ViewCashflow cashflowPanel;
    private ViewProfile profilePanel;

    
    public ViewDashboard() {
        initComponents();
        
        dashboardPanel = new ViewDashboardReal();
        main.add(dashboardPanel, "dashboard");
        
        CardLayout cl = (CardLayout) main.getLayout();
        cl.show(main, "dashboard");
        
        refreshDashboard();
    
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        btnKeuangan = new javax.swing.JButton();
        btnCashflow = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        main = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 600));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(150, 300));

        btnDashboard.setText("Dashboard");
        btnDashboard.addActionListener(this::btnDashboardActionPerformed);

        btnKeuangan.setText("Keuangan");
        btnKeuangan.addActionListener(this::btnKeuanganActionPerformed);

        btnCashflow.setText("Cashflow");
        btnCashflow.addActionListener(this::btnCashflowActionPerformed);

        btnProfile.setText("Profile");
        btnProfile.addActionListener(this::btnProfileActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FINBISKU");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKeuangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCashflow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnDashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKeuangan)
                .addGap(12, 12, 12)
                .addComponent(btnCashflow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProfile)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        main.setMaximumSize(new java.awt.Dimension(0, 0));
        main.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        refreshDashboard();
        CardLayout cl = (CardLayout) main.getLayout();
        cl.show(main, "dashboard");
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void refreshDashboard() {
        ControllerDashboard controller = new ControllerDashboard();
        dashboardPanel.setTotalPemasukan(controller.getTotalPemasukan());
        dashboardPanel.setTotalPengeluaran(controller.getTotalPengeluaran());
        dashboardPanel.setTotalSaldo(controller.getTotalSaldo());
        dashboardPanel.setDataDashboard(controller.getDataDashboard());
    }

    private void btnKeuanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeuanganActionPerformed
        // TODO add your handling code here:
        try {

            if (keuanganPanel == null) {
                keuanganPanel = new ViewKeuangan();
                main.add(keuanganPanel, "keuangan");
            }

            CardLayout cl = (CardLayout) main.getLayout();
            cl.show(main, "keuangan");

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Halaman Keuangan belum siap\n\n" + e.getMessage()
            );
        }
    }//GEN-LAST:event_btnKeuanganActionPerformed

    private void btnCashflowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCashflowActionPerformed
        // TODO add your handling code here:
        try {

            if (cashflowPanel == null) {
                cashflowPanel = new ViewCashflow();
                main.add(cashflowPanel, "cashflow");
            }

            CardLayout cl = (CardLayout) main.getLayout();
            cl.show(main, "cashflow");

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Halaman Cashflow belum siap\n\n" + e.getMessage()
            );
        }
    }//GEN-LAST:event_btnCashflowActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
        try {

            if (profilePanel == null) {
                profilePanel = new ViewProfile();
                main.add(profilePanel, "profile");
            }

            CardLayout cl = (CardLayout) main.getLayout();
            cl.show(main, "profile");

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Halaman Profile belum siap\n\n" + e.getMessage()
            );
        }
    }//GEN-LAST:event_btnProfileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCashflow;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnKeuangan;
    private javax.swing.JButton btnProfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLayeredPane main;
    // End of variables declaration//GEN-END:variables
}
