/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Content;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Controller.ControllerKeuangan;
import Model.ModelTransaksi;
import Controller.ControllerCashflow;
import Controller.ControllerKeuangan;
import java.awt.event.ActionListener;

/**
 *
 * @author Felda Muffarihati
 */
public class ViewKeuangan extends javax.swing.JPanel {

    private ControllerCashflow controlCashflow = new ControllerCashflow();

    private ControllerKeuangan control;
    private DefaultTableModel modelTabel;
    private int idTerpilih;

    public ViewKeuangan() {
        initComponents();
        control = new ControllerKeuangan();
        refreshTabel();

        SpinnerTanggal.setEditor(
                new javax.swing.JSpinner.DateEditor(
                        SpinnerTanggal,
                        "yyyy-MM-dd"
                )
        );

        refreshTabel();

        tabelKeuangan.getColumnModel().getColumn(0).setMinWidth(0);
        tabelKeuangan.getColumnModel().getColumn(0).setMaxWidth(0);
        tabelKeuangan.getColumnModel().getColumn(0).setPreferredWidth(0);
    }

    private void refreshTabel() {
        DefaultTableModel model = (DefaultTableModel) tabelKeuangan.getModel();
        model.setRowCount(0); //

        ArrayList<Model.ModelTransaksi> list = control.ambilSemuaModelTransaksi();

        if (list != null) {
            for (Model.ModelTransaksi t : list) {
                Object[] row = {
                    t.idTransaksi,
                    t.tanggal,
                    t.jenis,
                    t.kategori,
                    t.nominal,
                    t.keterangan
                };
                model.addRow(row);
            }
        }
    }

    private void clearForm() {
        SpinnerTanggal.setValue(new java.util.Date());

        cbJenis_Transaksi.setSelectedIndex(0);
        cbKategori.setSelectedIndex(0);

        txtNominal.setText("");
        txtKeterangan.setText("");

        idTerpilih = -1;
    }

    public void addDeleteListener(ActionListener listener) {
        btnHapus.addActionListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelKeuangan = new javax.swing.JTable();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        Label_Tanggal = new javax.swing.JLabel();
        Label_Jenis = new javax.swing.JLabel();
        cbJenis_Transaksi = new javax.swing.JComboBox<>();
        txtKeterangan = new javax.swing.JTextField();
        Label_Keterangan = new javax.swing.JLabel();
        Label_Nominal = new javax.swing.JLabel();
        Label_Kategori = new javax.swing.JLabel();
        cbKategori = new javax.swing.JComboBox<>();
        txtNominal = new javax.swing.JTextField();
        SpinnerTanggal = new javax.swing.JSpinner();

        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setFocusable(false);
        setPreferredSize(new java.awt.Dimension(400, 300));

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("KEUANGAN");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setOpaque(true);

        tabelKeuangan.setBackground(new java.awt.Color(204, 255, 255));
        tabelKeuangan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Tanggal", "Jenis", "Kategori", "Nominal", "Keterangan"
            }
        ));
        tabelKeuangan.setShowHorizontalLines(true);
        tabelKeuangan.setShowVerticalLines(true);
        tabelKeuangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelKeuanganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelKeuangan);

        btnSimpan.setBackground(new java.awt.Color(204, 255, 204));
        btnSimpan.setText("Simpan");
        btnSimpan.setBorderPainted(false);
        btnSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);

        btnEdit.setBackground(new java.awt.Color(255, 204, 153));
        btnEdit.setText("Edit");
        btnEdit.setBorderPainted(false);
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.addActionListener(this::btnEditActionPerformed);

        btnHapus.setBackground(new java.awt.Color(255, 153, 153));
        btnHapus.setText("Hapus");
        btnHapus.setBorderPainted(false);
        btnHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        btnClear.setBackground(new java.awt.Color(153, 204, 255));
        btnClear.setText("Clear");
        btnClear.setBorderPainted(false);
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear.addActionListener(this::btnClearActionPerformed);

        Label_Tanggal.setText("Tanggal");

        Label_Jenis.setText("Jenis");

        cbJenis_Transaksi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pemasukan", "Pengeluaran" }));

        Label_Keterangan.setText("Keterangan");

        Label_Nominal.setText("Nominal");

        Label_Kategori.setText("Kategori");

        cbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Penjualan", "Pembelian", "Sewa", "Utilitas", "Suplies", "Pajak", "Gaji Karyawan", "Modal" }));

        SpinnerTanggal.setModel(new javax.swing.SpinnerDateModel());
        SpinnerTanggal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Label_Tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Label_Jenis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Label_Keterangan))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbJenis_Transaksi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(SpinnerTanggal))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Label_Nominal, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                            .addComponent(Label_Kategori, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbKategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtNominal)))
                                    .addComponent(txtKeterangan)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(Label_Tanggal))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SpinnerTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Label_Nominal)
                        .addComponent(txtNominal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbJenis_Transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_Kategori))
                        .addComponent(Label_Jenis, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Keterangan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear)
                    .addComponent(btnHapus)
                    .addComponent(btnEdit)
                    .addComponent(btnSimpan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed

        if (idTerpilih == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data pada tabel yang ingin diubah terlebih dahulu!");
            return;
        }

        try {
            String jenis = cbJenis_Transaksi.getSelectedItem().toString();
            String kat = cbKategori.getSelectedItem().toString();
            String ket = txtKeterangan.getText().trim();

            String teksNominal = txtNominal.getText().replaceAll("\\D", "");
            
            if (teksNominal.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nominal tidak boleh kosong!");
                return;
            }

            double nom = Double.parseDouble(teksNominal);

            if (nom <= 0) {
                JOptionPane.showMessageDialog(this, "Nominal harus lebih dari 0!");
                return;
            }

            boolean sukses = control.ubahTransaksi(idTerpilih, jenis, kat, nom, ket);

            if (sukses) {
                JOptionPane.showMessageDialog(this, "Data transaksi berhasil diperbarui!");
                refreshTabel();
                clearForm();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal memperbarui data.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed

        if (txtNominal.getText().trim().isEmpty() || txtKeterangan.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua form input wajib diisi!");
            return;
        }

        java.util.Date dateDariSpinner = (java.util.Date) SpinnerTanggal.getValue();
        java.text.SimpleDateFormat formatMsql = new java.text.SimpleDateFormat("yyyy-MM-dd");

        String tgl = formatMsql.format(dateDariSpinner);
        String jenis = cbJenis_Transaksi.getSelectedItem().toString();
        String kat = cbKategori.getSelectedItem().toString();
        double nom;
        try {
            nom = Double.parseDouble(txtNominal.getText());

            if (nom <= 0) {
                JOptionPane.showMessageDialog(this,
                        "Nominal harus lebih dari 0!");
                return;
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Nominal harus berupa angka!");
            return;
        }
        String ket = txtKeterangan.getText().trim();

        boolean sukses = control.simpanTransaksi(tgl, jenis, kat, nom, ket);

        if (sukses) {
            JOptionPane.showMessageDialog(this, "Data transaksi berhasil disimpan!");
            refreshTabel();
            clearForm();
        } else {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data ke database.");
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void tabelKeuanganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelKeuanganMouseClicked
        
        int baris = tabelKeuangan.getSelectedRow();
        if (baris != -1) {
            idTerpilih = Integer.parseInt(tabelKeuangan.getValueAt(baris, 0).toString());

            try {
                String tglString = tabelKeuangan.getValueAt(baris, 1).toString();
                java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
                java.util.Date dateParsed = sdf.parse(tglString);
                SpinnerTanggal.setValue(dateParsed);
            } catch (Exception e) {
                System.out.println("Gagal set tanggal : " + e.getMessage());
            }

            cbJenis_Transaksi.setSelectedItem(tabelKeuangan.getValueAt(baris, 2).toString());
            cbKategori.setSelectedItem(tabelKeuangan.getValueAt(baris, 3).toString());
            
            String nilaiTabel = tabelKeuangan.getValueAt(baris, 4).toString();
            String nilaiBersih = nilaiTabel.replaceAll("\\D", "");
            txtNominal.setText(nilaiBersih);

            txtKeterangan.setText(tabelKeuangan.getValueAt(baris, 5).toString());
        }
    }//GEN-LAST:event_tabelKeuanganMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed

        clearForm();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed

        if (idTerpilih == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data pada tabel yang ingin dihapus terlebih dahulu!");
            return;
        } else {

        }
        int konfirmasi = JOptionPane.showConfirmDialog(this,
                "Apakah Anda yakin ingin menghapus transaksi ini?",
                "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

        if (konfirmasi == JOptionPane.YES_OPTION) {
            boolean sukses = control.hapusTransaksi(idTerpilih);

            if (sukses) {
                JOptionPane.showMessageDialog(this, "Data transaksi telah dihapus!");
                refreshTabel();
                clearForm();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menghapus data.");
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_Jenis;
    private javax.swing.JLabel Label_Kategori;
    private javax.swing.JLabel Label_Keterangan;
    private javax.swing.JLabel Label_Nominal;
    private javax.swing.JLabel Label_Tanggal;
    private javax.swing.JSpinner SpinnerTanggal;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbJenis_Transaksi;
    private javax.swing.JComboBox<String> cbKategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelKeuangan;
    private javax.swing.JTextField txtKeterangan;
    private javax.swing.JTextField txtNominal;
    // End of variables declaration//GEN-END:variables
}
