/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Content;

import Controller.ControllerDashboard;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Felda Muffarihati
 */
public class ViewDashboardReal extends javax.swing.JPanel {
    
    private Object[][] dataDashboard;
    
    public ViewDashboardReal() {
        initComponents();
        
        ControllerDashboard controlDashboard = new ControllerDashboard();

        Object[][] data = controlDashboard.getDataDashboard();
        this.setDataDashboard(data);

        txtTotal_Masuk.setEditable(false);
        
        txtTotal_Masuk.setEditable(false);
        
        txtTotal_Masuk.setEditable(false);
        txtTotal_Keluar.setEditable(false);
        txtTotal_Saldo.setEditable(false);
        
        txtTotal_Masuk.setFocusable(false);
        txtTotal_Keluar.setFocusable(false);
        txtTotal_Saldo.setFocusable(false);

        txtTotal_Masuk.setPreferredSize(new java.awt.Dimension(125,60));
        txtTotal_Keluar.setPreferredSize(new java.awt.Dimension(125,60));
        txtTotal_Saldo.setPreferredSize(new java.awt.Dimension(125,60));
        
        btnCari.addActionListener(evt -> cariData());
        
        loadData();
    }

    public void loadData() {
        ControllerDashboard controller = new ControllerDashboard();
        setTotalPemasukan(controller.getTotalPemasukan());
        setTotalPengeluaran(controller.getTotalPengeluaran());
        setTotalSaldo(controller.getTotalSaldo());
        setDataDashboard(controller.getDataDashboard());
    }
    
    public void setTotalPemasukan(double total) {

    if(total <= 0){
        txtTotal_Masuk.setText("Total Pemasukan");
    } else{
        txtTotal_Masuk.setText(
            String.format("Total Pemasukan: Rp %,.0f", total)
        );
    }
    }

    public void setTotalPengeluaran(double total) {

    if(total <= 0){
        txtTotal_Keluar.setText("Total Pengeluaran");
    } else {
        txtTotal_Keluar.setText(
            String.format("Total Pengeluaran: Rp %,.0f", total)
        );
    }
    }

    public void setTotalSaldo(double total) {
        txtTotal_Saldo.setText("Total Saldo: Rp " + total);
    }
    
    public void setDataDashboard(Object[][] data) {

        this.dataDashboard = data;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel(); 
        model.setRowCount(0);
        if (data != null) {
            for (Object[] row : data) {
                model.addRow(row);
            }
        }
    }
    
  
    
    private void cariData() {

        if (dataDashboard == null) {
            return;
        }

        String keyword = txtCari.getText().trim().toLowerCase();

        javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) jTable1.getModel();

        model.setRowCount(0);

        for (Object[] row : dataDashboard) {

            boolean cocok = keyword.isEmpty();

            if (!cocok) {

                for (Object cell : row) {

                    if (cell != null &&
                        cell.toString().toLowerCase().contains(keyword)) {

                        cocok = true;
                        break;
                    }
                }
            }

            if (cocok) {
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtTotal_Masuk = new javax.swing.JTextField();
        txtTotal_Keluar = new javax.swing.JTextField();
        txtTotal_Saldo = new javax.swing.JTextField();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(400, 300));

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DASHBOARD");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setOpaque(true);

        jTable1.setBackground(new java.awt.Color(204, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tanggal", "Jenis", "Kategori", "Nominal", "Keterangan"
            }
        ));
        jTable1.setShowGrid(false);
        jTable1.setShowHorizontalLines(true);
        jTable1.setShowVerticalLines(true);
        jScrollPane1.setViewportView(jTable1);

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        txtTotal_Masuk.setBackground(new java.awt.Color(204, 255, 204));
        txtTotal_Masuk.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTotal_Masuk.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotal_Masuk.setText("Total Pemasukan");
        txtTotal_Masuk.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 153), 2, true));

        txtTotal_Keluar.setBackground(new java.awt.Color(255, 204, 204));
        txtTotal_Keluar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTotal_Keluar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotal_Keluar.setText("Total Pengeluaran");
        txtTotal_Keluar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 153), 2, true));
        txtTotal_Keluar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txtTotal_Saldo.setBackground(new java.awt.Color(204, 204, 255));
        txtTotal_Saldo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTotal_Saldo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotal_Saldo.setText("Total Saldo");
        txtTotal_Saldo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 2, true));
        txtTotal_Saldo.setOpaque(true);

        btnCari.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCari.setText("Cari");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Selamat datang di Sistem Pengelolaan Keuangan UMKM !");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtCari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtTotal_Masuk, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal_Keluar, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal_Saldo, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtTotal_Masuk, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(txtTotal_Keluar, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTotal_Saldo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtTotal_Keluar;
    private javax.swing.JTextField txtTotal_Masuk;
    private javax.swing.JTextField txtTotal_Saldo;
    // End of variables declaration//GEN-END:variables
}
