/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Content;

/**
 *
 * @author Felda Muffarihati
 */
public class ViewCashflow extends javax.swing.JPanel {
    private Controller.ControllerCashflow controlCashflow;

    public ViewCashflow() {
        initComponents();
        
        controlCashflow = new Controller.ControllerCashflow();

    loadCashflow();

    cbP_Bulan.addActionListener(e -> loadCashflow());
    cbP_Tahun.addActionListener(e -> loadCashflow());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        LabelCahflow = new javax.swing.JLabel();
        panelStatus = new javax.swing.JPanel();
        LabelStatus = new javax.swing.JLabel();
        cbP_Bulan = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabel_Cashflow = new javax.swing.JTable();
        cbP_Tahun = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setPreferredSize(new java.awt.Dimension(400, 300));

        LabelCahflow.setBackground(new java.awt.Color(0, 153, 153));
        LabelCahflow.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LabelCahflow.setForeground(new java.awt.Color(255, 255, 255));
        LabelCahflow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelCahflow.setText("CASHFLOW");
        LabelCahflow.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LabelCahflow.setOpaque(true);

        panelStatus.setBackground(new java.awt.Color(102, 102, 102));

        LabelStatus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelStatus.setForeground(new java.awt.Color(255, 255, 255));
        LabelStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelStatus.setText("Kondisi Keuangan Bulan ini :");

        javax.swing.GroupLayout panelStatusLayout = new javax.swing.GroupLayout(panelStatus);
        panelStatus.setLayout(panelStatusLayout);
        panelStatusLayout.setHorizontalGroup(
            panelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelStatusLayout.setVerticalGroup(
            panelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStatusLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(LabelStatus)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        cbP_Bulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));

        Tabel_Cashflow.setBackground(new java.awt.Color(204, 255, 255));
        Tabel_Cashflow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kategori", "Jenis", "Total"
            }
        ));
        Tabel_Cashflow.setShowHorizontalLines(true);
        Tabel_Cashflow.setShowVerticalLines(true);
        jScrollPane2.setViewportView(Tabel_Cashflow);

        cbP_Tahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020", "2021", "2022", "2023", "2024", "2025", "2026" }));

        jLabel1.setText("Periode :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelCahflow, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbP_Bulan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbP_Tahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelCahflow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbP_Bulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbP_Tahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelCahflow;
    private javax.swing.JLabel LabelStatus;
    private javax.swing.JTable Tabel_Cashflow;
    private javax.swing.JComboBox<String> cbP_Bulan;
    private javax.swing.JComboBox<String> cbP_Tahun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel panelStatus;
    // End of variables declaration//GEN-END:variables

    private void loadCashflow() {
        String bulan = cbP_Bulan.getSelectedItem().toString();
        int tahun = Integer.parseInt(cbP_Tahun.getSelectedItem().toString());

        double pemasukan   = controlCashflow.getTotalPemasukan(bulan, tahun);
        double pengeluaran = controlCashflow.getTotalPengeluaran(bulan, tahun);
        double saldo       = pemasukan - pengeluaran;

        javax.swing.table.DefaultTableModel model =
                (javax.swing.table.DefaultTableModel) Tabel_Cashflow.getModel();
        model.setRowCount(0);

        java.util.ArrayList<Model.ModelRekapKategori> listRekap =
                controlCashflow.getRekapPerKategori(bulan, tahun);

        java.text.NumberFormat fmt =
                java.text.NumberFormat.getCurrencyInstance(new java.util.Locale("id", "ID"));

        if (listRekap.isEmpty()) {
            model.addRow(new Object[]{ "-", "-", "Tidak ada data" });
        } else {
            for (Model.ModelRekapKategori rekap : listRekap) {
                model.addRow(new Object[]{
                    rekap.getKategori(),
                    rekap.getJenis(),
                    fmt.format(rekap.getTotal())
                });
            }
        }

        tampilkanStatus(saldo);
    }

    private void tampilkanStatus(double saldo) {
        if (saldo > 0) {
            LabelStatus.setText("Kondisi Keuangan Bulan Ini : SURPLUS");
            panelStatus.setBackground(new java.awt.Color(76, 175, 80));
        } else if (saldo < 0) {
            LabelStatus.setText("Kondisi Keuangan Bulan Ini : DEFISIT");
            panelStatus.setBackground(new java.awt.Color(244, 67, 54));
        } else {
            LabelStatus.setText("Kondisi Keuangan Bulan Ini : IMPAS");
            panelStatus.setBackground(new java.awt.Color(255, 193, 7));
        }
    } 
}
